[build]
  command = "npm run build"
  
[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".next/**,.netlify/**,node_modules/**,*.cache/**,*.pack"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"