[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".next/**,.netlify/**,node_modules/**,*.cache/**,*.pack"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200